name: Daily Empty Commit

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grants write permission to the GITHUB_TOKEN

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create an Empty File
        run: |
          # Create a temporary empty file to ensure there's something to commit
          echo "" > .tmp_empty_commit

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: daily empty commit"
          file_pattern: ".tmp_empty_commit"

      - name: Cleanup
        run: |
          # Remove the temporary file after committing
          rm .tmp_empty_commit